services:
  front:
    image: cuu2253/joyful-village:latest
    ports:
      - "3000:3000"
    restart: always
    container_name: front
    depends_on:
      - back
    environment:
      - NEXT_PUBLIC_API_URL=http://43.200.1.5
      - NEXT_PUBLIC_MEDIA_URL=http://43.200.1.5/media/  # Use backend URL for media access
    # ❌ Removed media-storage volume (Frontend does NOT need it)
