# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy Joyfulvillage

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : checkout source code
        uses : actions/checkout@v4
      - name: Check Node v
        run: node -v
      - name: Install Dependencies
        run: npm install
      - name: Build Next Prod
        run: npm run build
      - name: Build Docker Image
        run: docker build -t cuu2253/joyful-village:latest .
      - name: Push Docker Image
        run: |
          docker login -u cuu2253 -p {{ secrets.DOCKER_HUB_TOKEN }}
          docker push cuu2253/joyful-village:latest
      # - name: zip create 
      #   run: zip -qq -r ./joyful-village-front.zip ./.next/ ./appspec.yml ./deploy.sh ./public
      #   shell: bash
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
      #     aws-secret-access-key: ${{ secrets.CICD_SECERET_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      # - name: Upload to S3 
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.CICD_ACCESS_KEY }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.CICD_SECERET_KEY }}
      #   run: |
      #     aws s3 cp --region us-west-2 ./editor-front.zip s3://deform-gongbae/editor-front.zip
      # - name: Deploy # Deploy to EC2
      #   run: aws deploy create-deployment
      #     --application-name deform-editor
      #     --deployment-config-name CodeDeployDefault.AllAtOnce
      #     --file-exists-behavior OVERWRITE
      #     --deployment-group-name deform-editor
      #     --s3-location bucket=deform-gongbae,key=editor-front.zip,bundleType=zip